# raise Exception('your exception', 8, 9, 0, 9)
for i in range(5):
    print(i)